#!/bin/bash
# use this file to make bash profile look like parrot os
# Define some basic colors using tput (8-bit color: 256 colors)
bright_red="\[$(tput setaf 196)\]"
orange="\[$(tput setaf 172)\]"
blue="\[$(tput setaf 21)\]"
purple="\[$(tput setaf 129)\]"
red="\[$(tput setaf 160)\]"
cyan="\[$(tput setaf 51)\]"
green="\[$(tput setaf 46)\]"
yellow="\[$(tput setaf 220)\]"
reset="\[$(tput sgr0)\]"
bold="\[$(tput bold)\]"

# Define basic colors to be used in prompt
## The color for username (green, for root user: bright_red)
username_color="${reset}${bold}${green}\$([[ \${EUID} == 0 ]] && echo \"${bright_red}\")";
## Color of @ and ✗ symbols (yellow)
at_color=$reset$bold$yellow
## Color of host/pc-name (cyan)
host_color=$reset$bold$cyan
## Color of current working directory (purple)
directory_color=$reset$purple
## Color for other characters (like the arrow)
etc_color=$reset$red
# If last operation did not succeded, add [✗]- to the prompt
on_error="\$([[ \$? != 0 ]] && echo \"${etc_color}[${at_color}✗${etc_color}]─\")"
# The last symbol in prompt ($, for root user: #)
symbol="${reset}${bold}${bright_red}$(if [[ ${EUID} == 0 ]]; then echo '#'; else echo '$'; fi)"


# Setup the prompt/prefix for linux terminal
PS1="${etc_color}┌─${on_error}[";
PS1+="${username_color}\u"; # \u=Username
PS1+="${at_color}@";
PS1+="${host_color}\h" #\h=Host
PS1+="${etc_color}]-[";
PS1+="${directory_color}\w"; # \w=Working directory
PS1+="${etc_color}]\n└──╼ "; # \n=New Line
PS1+="${symbol} ${green}";

export PS1
