# Inserts a blank line between shell prompts
add_newline = false
continuation_prompt = "▶▶(green) "
command_timeout = 1000

format = """
$username$hostname$directory$battery$sudo$cmd_duration$aws$conda$dart$docker_context$elixir$elm$git_branch$golang$hg_branch$java$julia$nim$nix_shell$nodejs$package$perl$php$python$ruby$rust$swift$haskell
$character
"""
#$character

### PROMPT

[character] 
# success_symbol = "[└](bold green)[](bold green)" # looks nicer but in fish adds 2 extra space chars
success_symbol = "[└](bold green)[](bold green)"
error_symbol = "[└](bold green)[✗](bold red)"

[directory]
style = "purple"
read_only_style = "red"
read_only = " "
truncation_length = 5
truncation_symbol = ".../"
format = "[\\[](bold red)[$path]($style)[\\]](bold red)[$read_only]($read_only_style) "

[username]
show_always = true
style_user = "green"
style_root = "bold red"
format = "[┌](bold green)[\\[](bold red)[$user]($style)[@](yellow)"

[hostname]
disabled = false
ssh_only = false
ssh_symbol = ""
format = "[$hostname$ssh_symbol]($style)[\\]](bold red)[::](bold yellow)"
style = "cyan"

[sudo]
symbol = " "
style = "bold bright-purple"
disabled = false
format = "[$symbol]($style)"

[cmd_duration]
min_time = 5000
style = "yellow"
format = "[ $duration]($style) "
disabled = false

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = " "

[haskell]
symbol = " "
